launchdarkly/ldcli

cmd/quickstart.go, internal/quickstart/choose_sdk.go, internal/quickstart/container.go, internal/quickstart/create_flag.go, internal/quickstart/messages.go, internal/quickstart/show_sdk_instructions.go, internal/quickstart/toggle_flag.go, internal/sdks/sdks.go, internal/sdks/sdks_test.go
Refactor container to use more messages.
=> chore: refactor container

internal/quickstart/messages.go
now sends a tea.Msg instead of tea.Cmd!
=> fix: fix err messages for toggle flag command

internal/quickstart/toggle_flag.go
otherwise users might not know where to check for updates 🙃
=> fix: update copy on toggle flag step to call out env

internal/quickstart/container.go
=> fix: Show the current step and total steps during setup

.goreleaser.yaml
- **add ldcli to our existing homebrew tap**
=> feat: add ldcli formula to homebrew-tap

internal/quickstart/container.go
=> fix: fix the step count

.goreleaser.yaml
- **remove id from homebrew config on .goreleaser.yaml**
=> fix: remove id from goreleaser homebrew build config

internal/quickstart/container.go, internal/quickstart/show_sdk_instructions.go
=> feat: add spinner to show sdk step

internal/quickstart/messages.go
No longer return an error when a 409 error code is returned and instead proceed with the existing key for the remainder of the setup.
=> fix: allow users to use existing flags during setup

.goreleaser.yaml
Story details: https://app.shortcut.com/launchdarkly/story/239334
Added arm64 image as well. Changed some formatting
=> chore: add arm64 docker image

.github/actions/publish/action.yml, .github/workflows/release-please.yml
We want to create and publish docker images. To do so we need to retrieve the docker use and token so that we can upload our image.
=> chore: retrieve docker user and token from aws and login to docker

internal/quickstart/container.go, internal/quickstart/show_sdk_instructions.go
=> fix: update show sdk instructions verbiage

README.md
=> chore: add prerelease warning

.github/workflows/manual-publish.yml
Added a manual-publish.yml file to create the manual-publish workflow
=> build: create manual publish gh workflow

.github/actions/publish/action.yml, PROVENANCE.md, README.md
=> build: only hashing .tar.gz archives for provenance

.github/workflows/release-please.yml
=> build: fixing workflow output for provenance generation

internal/quickstart/choose_sdk.go, internal/quickstart/toggle_flag.go
mobile sdk flag toggle message is now `Check your application to see the change!`
[Asked on slack for opinions on what the message should be.](https://launchdarkly.slack.com/archives/C06KW03D8F7/p1712704665468729)
=> feat: change flag toggle success message for mobile sdks

internal/quickstart/choose_sdk.go, internal/quickstart/messages.go, internal/quickstart/show_sdk_instructions.go, internal/sdks/sdk_instructions/react.md, internal/sdks/sdks.go, internal/sdks/sdks_test.go
Adding this one as its own PR because it's a little more involved than just adding the `.md` file.
=> chore: add react sdk instructions

internal/quickstart/choose_sdk.go, internal/quickstart/container.go, internal/quickstart/create_flag.go, internal/quickstart/messages.go, internal/quickstart/show_sdk_instructions.go, internal/quickstart/toggle_flag.go
* messages - end with Msg
* commands - more descriptive verb than "send"
=> chore: Rename messages and commands

cmd/quickstart.go, cmd/root.go, internal/quickstart/container.go, internal/quickstart/messages.go, internal/quickstart/show_sdk_instructions.go
Passes in an environments client instead of creating a new one in a setup step.
=> chore: Use env client

internal/quickstart/container.go
Per feedback, make it more clear that this command will actually be doing.
=> feat: add extra instructions on first step

PROVENANCE.md, release-please-config.json
=> docs: slight update to PROVENANCE.md

.github/workflows/release-please.yml
=> build: Never do a dry run to publish the npm package for a release

internal/sdks/sdk_instructions/python.md
missed the very last step, noticed when recording demo 🤦‍♀️
=> fix: python instructions

README.md
=> chore: update readme for config + env variables

cmd/config/config.go, cmd/resources/resources.go, internal/config/config.go, internal/output/plaintext_fns.go
=> fix: Fix showing analytics-opt-out in config as missing

internal/sdks/sdk_instructions/android.md, internal/sdks/sdk_instructions/c-server.md, internal/sdks/sdk_instructions/dotnet-client.md, internal/sdks/sdk_instructions/dotnet-server.md, internal/sdks/sdk_instructions/go.md, internal/sdks/sdk_instructions/haskell-server.md, internal/sdks/sdk_instructions/ios-swift.md, internal/sdks/sdk_instructions/java.md, internal/sdks/sdk_instructions/js.md, internal/sdks/sdk_instructions/lua-server.md, internal/sdks/sdk_instructions/node-client.md, internal/sdks/sdk_instructions/node-server.md, internal/sdks/sdk_instructions/php.md, internal/sdks/sdk_instructions/python.md, internal/sdks/sdk_instructions/ruby.md, internal/sdks/sdk_instructions/rust.md, internal/sdks/sdk_instructions/vue.md
Update SDK instructions to be consistent with the /get-started instructions in the web app.
=> feat: Update SDK instructions

cmd/environments/get.go, cmd/flags/create.go, cmd/flags/update.go, cmd/members/invite.go, cmd/projects/create.go, cmd/projects/list.go
=> fix: Use new error output fn for all commands

internal/projects/projects.go
=> fix: remove get projects limit

internal/analytics/client.go, internal/quickstart/container.go, internal/quickstart/messages.go
- **added flag toggled client methods**
- **added cmd in messages**
- **track flag toggle in container**
=> feat: track setup flag toggle event

README.md
[SC-239040](https://app.shortcut.com/launchdarkly/story/239040/ldcli-readme-updates)
Minor edits to add links, improve parallelism, fix typos, etc.
=> docs: readme updates (copyedits)

internal/analytics/client.go, main.go
=> fix: Don't hardcode version for tracking events

.github/workflows/release-please.yml
=> chore: Remove release-type from release please workflow.

cmd/resources/resources.go
Double-checked this, and we can remove the TODO.
=> chore: Use viper instead of pflag to get --data

internal/quickstart/container.go, internal/quickstart/messages.go, internal/quickstart/toggle_flag.go
Throttles toggling the flag so the user doesn't get rate-limited.
=> feat: throttle flag toggle

cmd/cmdtest.go, cmd/validators/validators.go, cmd/validators/validators_test.go
=> feat: Show link to create access token when it's missing

cmd/resources/resource_utils.go, cmd/root.go
before:
```
$ ldcli completion --help
Generate the autocompletion script for ldcli for the specified shell.
See each sub-command's help for details on how to use the generated script.
```
after:
```
$ ldcli completion --help
Generate the autocompletion script for ldcli for the specified shell.
See each command's help for details on how to use the generated script.
```
Add any other context …
=> feat: Update completion command help text

internal/quickstart/toggle_flag.go
After toggling the flag during setup, show a link to troubleshooting help.
=> chore: Add troubleshooting link for flag toggle

internal/sdks/sdk_instructions/go.md
tried actually setting these up for the next demo day recording and noticed these were off. will let the quickstart team know also
=> fix: fix go sdk instructions

cmd/resources/resource_cmds.go, cmd/resources/resources.go, cmd/root.go, cmd/templates.go
```shell
ldcli teams get --help
```
=> feat: break out required and optional flags in subcommand help

cmd/config/config.go, cmd/root.go, internal/config/config.go
Changes config file to `XDG_CONFIG_HOME/ldcli/config.yml` (`~/.config/ldcli/config.yml`).
=> chore: Change config file to XDG_CONFIG_HOME/ldcli/config.yml

cmd/quickstart.go
TBD on how we track "CLI command completed" for the setup command.
=> fix: Track event when user runs the setup command

internal/quickstart/container.go, internal/quickstart/messages.go
Track "CLI Command Completed" event when user gets to toggle flag setup view.
=> feat: track setup completed

cmd/resources/resources.go
Render command long description as markdown.
=> feat: Render help as markdown

internal/sdks/sdk_instructions/java.md
The code wasn't intended enough and looked off.
=> fix: Fix java SDK sample

README.md, release-please-config.json
=> chore: update readme with installation steps

README.md
[SC-245120](https://app.shortcut.com/launchdarkly/story/245120/bug-fix-npm-install-instructions-for-cli)
=> docs: fix npm install instructions

internal/config/config_service.go
merged my last pr in too fast 🙈
=> fix: client request in config service

internal/analytics/client.go
Updates tracking URL to use new internal one.
=> chore: Update tracking URL

README.md
[SC-246308](https://app.shortcut.com/launchdarkly/story/246308/update-ldcli-instructions-product-docs-readme-for-linux-windows-installations)
See also https://github.com/launchdarkly/ld-docs-private/pull/4447
=> docs: Linux executable now available

.github/workflows/check-openapi-updates.yml, Makefile, scripts/check-openapi-changed.sh
Creates a workflow to check if we need to update the OpenAPI JSON which would mean we want to update the resource commands.
Running locally with [act](https://github.com/nektos/act), I get this, which seems to work for the failure case.
```
> ldcli act schedule
INFO[0000] Using docker host 'unix:///var/run/docker.sock', and daemon socket 'unix:///var/run/docker.sock'
WARN  ⚠ You are using Apple M-series chip and you have not specified container architecture, you might encounter issues while running act. If so, try running it with '--container-architecture linux/amd64'. ⚠
INFO[0000] deleted cache: &{ID:2 Key:setup-go-linux-ubuntu20-go-1.20.14-dbf0229a07387f4ac54ccea26af1b7a62b30a71784a27319980c80a3fcd713fb Version:80c03ad9bc0f7552c128ae36020fe5294ef09c552e168fbe45ea237491c60cae …
```
=> chore: workflow to update openapi spec

cmd/login/login.go, cmd/root.go, cmd/templates.go
Adds login command skeleton with analytics tracking.
=> feat: Create login command

cmd/config/config.go, cmd/flags/archive.go, cmd/flags/toggle.go, cmd/login/login.go, cmd/members/invite.go, cmd/resources/resources.go, internal/output/resource_output.go
Refactors call to output a command error based on the output kind (json, plaintext, etc.).
=> chore: Refactor function

cmd/dev_server/dev_server.go, cmd/dev_server/overrides.go, cmd/dev_server/projects.go, cmd/dev_server/start_server.go, internal/dev_server/api/server.go
This just adds the ldCli command to sync projects.  I also added groups to the help output because it was getting difficult to parse.
Here's what it looked like before:
Here's what it looks like after
=> update ld cli commands

internal/dev_server/api/api.yaml, internal/dev_server/api/server.gen.go, internal/dev_server/api/server.go
we were not returning flag state in any of our responses and the api needs this to display the flags they can override.  So I added it to the get project response.  If you think we should have a different api lmk.
=> Add flag state

internal/dev_server/ui/src/App.css, internal/dev_server/ui/src/App.tsx, internal/dev_server/ui/vite.config.ts
Removing the hard-coded flags in favor of API-sourced flags.
=> feat: remove mock flags in devserver UI

.goreleaser.yaml, Dockerfile.goreleaser
=> [sc-248413] moonshots deploy ld dev server into the dev

internal/dev_server/ui/.prettierrc, internal/dev_server/ui/README.md, internal/dev_server/ui/src/App.css, internal/dev_server/ui/src/App.tsx, internal/dev_server/ui/src/IconProvider.tsx, internal/dev_server/ui/src/main.tsx, internal/dev_server/ui/vite.config.ts
Loom walkthrough [here](https://www.loom.com/share/b89dff39a5d24e86a1279f08523a4f4c), adding baseline support for managing overrides from the devserver UI
=> feat: Add support for flag overrides from the devserver UI

go.mod, go.sum, internal/dev_server/dev_server.go, vendor/github.com/adrg/xdg/CODE_OF_CONDUCT.md, vendor/github.com/adrg/xdg/CONTRIBUTING.md, vendor/github.com/adrg/xdg/LICENSE, vendor/github.com/adrg/xdg/README.md, vendor/github.com/adrg/xdg/base_dirs.go, vendor/github.com/adrg/xdg/codecov.yml, vendor/github.com/adrg/xdg/doc.go, vendor/github.com/adrg/xdg/internal/pathutil/pathutil.go, vendor/github.com/adrg/xdg/internal/pathutil/pathutil_plan9.go, vendor/github.com/adrg/xdg/internal/pathutil/pathutil_unix.go, vendor/github.com/adrg/xdg/internal/pathutil/pathutil_windows.go, vendor/github.com/adrg/xdg/paths_darwin.go, vendor/github.com/adrg/xdg/paths_plan9.go, vendor/github.com/adrg/xdg/paths_unix.go, vendor/github.com/adrg/xdg/paths_windows.go, vendor/github.com/adrg/xdg/user_dirs.go, vendor/github.com/adrg/xdg/xdg.go, vendor/modules.txt
Use `XDG_STATE_HOME` for db location.
=> feat: Move devserver db to XDG_STATE_HOME

internal/dev_server/api/api.yaml, internal/dev_server/api/server.gen.go, internal/dev_server/api/server.go, internal/dev_server/db/sqlite.go, internal/dev_server/model/project.go
This allows contexts and sourceEnvironmentKey to be patched on the project and I also updated the post to allow context creation.  I did not update the ldcli yet.
@mike-zorn I wasn't a 100% sure how to check if the contexts were correctly being applied.  I'm not too clear on how marshalling works and if things needed to be marshalled or unmarshalled or what not.  So if you can take a look at that, that would be great.
=> Add project patch

internal/dev_server/api/server.go
=> fix: fix override

internal/dev_server/adapters/sdk.go, internal/dev_server/sdk/cors.go, internal/dev_server/sdk/docs.go, internal/dev_server/sdk/get_server_flags.go, internal/dev_server/sdk/project_key_middleware.go, internal/dev_server/sdk/routes.go, internal/dev_server/sdk/server_flags.go, internal/dev_server/sdk/stream_server_flags.go
This adds support for mobile and PHP SDKs. It also relocates the list of the
supported endpoints to the package docs instead of a random comment.
=> feat: add mobile & PHP support

internal/login/client.go, internal/login/client_test.go, internal/login/login.go, internal/resources/client.go
When logging in, if there isn't a response body for a > 4XX response, manually create one.
=> chore: Fix error response with no body

internal/dev_server/README.md, internal/dev_server/api/server.go, internal/dev_server/sdk/stream_client_flags.go, internal/dev_server/ui/README.md
Documents the build process for the dev server. Also fixes a go generate command and removes an extraneous comment.
=> fix: add documentation of the build process

internal/dev_server/dev_server.go
Used the wrong type of log statement - fixed that.
=> fix: startup logging

internal/dev_server/sdk/cors.go
=> fix: add credentials to cors

.github/actions/mike-test-build/action.yml, .goreleaser.grcross.yaml, .goreleaser.zig.yaml, scripts/gr-cross-runner.sh, scripts/zig-runner.sh
=> attempt xbuild

internal/dev_server/ui/src/App.tsx, internal/dev_server/ui/src/Flags.tsx, internal/dev_server/ui/src/ProjectSelector.tsx, internal/dev_server/ui/src/Sync.tsx, internal/dev_server/ui/src/util.ts
=> feat: Add Sync button for refreshing the state

Dockerfile.goreleaser
Reverts launchdarkly/ldcli#401
=> revert: Use ubuntu for the base image

.github/dependabot.yml
This PR adds auto-merge configuration for dependabot updates.
=> chore: Update dependabot configuration for auto-merge

.github/workflows/release-please.yml
This should fix build errors like [this one](https://github.com/launchdarkly/ldcli/actions/runs/15211461934/job/42808171292).
---
Related Jira issue: [FUN-800: fix release build](https://launchdarkly.atlassian.net/browse/FUN-800)
=> fix: [FUN-800] Update action version

.github/actions/publish/action.yml, .github/workflows/manual-publish.yml, .github/workflows/release-please.yml
---
Related Jira issue: [IDE-1660: Unable to push to homebrew tap from ldcli](https://launchdarkly.atlassian.net/browse/IDE-1660)
=> chore: [IDE-1660] Use internal goreleaser-cross image

.github/actions/publish/action.yml
---
Related Jira issue: [IDE-1709: Debug issues with release-please in ldcli](https://launchdarkly.atlassian.net/browse/IDE-1709)
=> fix: [IDE-1709] Another attempt at fixing
