cmd/flags/flags.go
cmd/flags/update.go

Based on Danny's suggestion, I went with creating a second command to create the `toggle-on` and `toggle-off` aliases

feat: add toggle on and off aliases to update flag

---

cmd/flags/update.go
cmd/flags/update_test.go
internal/flags/client.go
internal/quickstart/container.go
internal/quickstart/create_flag.go
internal/quickstart/messages.go
internal/quickstart/show_sdk_instructions.go
internal/quickstart/toggle_flag.go

Adds the remaining functionality for the toggle flag steps. Error handling will follow in a separate PR.

feat: add toggle flag step

---

internal/quickstart/create_flag.go

removes the placeholder text in the text input model and instead moves it up to the title.

fix: remove create flag placeholder text

---

internal/quickstart/show_sdk_instructions.go

fix: add instructions to continue from show sdk step

---

cmd/root.go

[story](https://app.shortcut.com/launchdarkly/story/239156/running-ldcli-completion-bash-should-not-require-access-token)
When a user runs `ldcli completion bash` they should not require the `access-token` flag.

fix: The completion command should not require any flags

---

internal/quickstart/choose_sdk.go
internal/quickstart/container.go
internal/quickstart/messages.go

A user can go back to choose another SDK once they're on the instructions page. We should show this in the help text once we have that.

feat: Can go back to choose SDK page from show SDK instructions

---

internal/quickstart/container.go
internal/quickstart/show_sdk_instructions.go

fix: Show SDK name in instructions

---

internal/quickstart/container.go

Using iota should be easier to read than magic numbers for looking at which step we're on in the setup command.

chore: Set up iota to describe steps instead of using ints

---

internal/quickstart/container.go

We show an error message when appropriate, but when they are no longer relevant we should hide it.

fix: Hide error messages after successful message

---

internal/quickstart/choose_sdk.go
internal/quickstart/container.go

When quitting setup, set the view to "" so it doesn't leave text behind in the terminal.

feat: Clear view when quitting setup

---

internal/quickstart/create_flag.go

fix: create flag prompt should be on the same line as text

---

cmd/root.go

Adding a link to the account settings page felt like it would be too long.

chore: update access-token flag help text

---

internal/quickstart/container.go

You can go back to any page in the setup flow (but not any farther). This doesn't save the flag name to show on the create flag page yet. I can follow up to have that page say
> Name your first feature flag (enter for default value "{the previously created flag name}"):

feat: Can go back to any previous setup page

---

internal/quickstart/choose_sdk.go
internal/quickstart/container.go
internal/quickstart/create_flag.go
internal/quickstart/help.go
internal/quickstart/show_sdk_instructions.go
internal/quickstart/toggle_flag.go

Error messages should show above the help text during setup.
Ignore the leftover SDK instructions line -- we can fix that in [this story](https://app.shortcut.com/launchdarkly/story/239306/make-sdk-instructions-scrollable).

fix: Setup error messages should show above help text

---

.github/workflows/manual-publish.yml

Looks like the previous manual run stopped due to the included if statement.
Also renamed the manual-publish workflow to `Manually Publish Images and Artifacts`

build: manual publish, remove if

---

internal/quickstart/container.go
internal/quickstart/messages.go
internal/quickstart/show_sdk_instructions.go
tools.go
vendor/github.com/charmbracelet/bubbles/viewport/keymap.go
vendor/github.com/charmbracelet/bubbles/viewport/viewport.go
vendor/modules.txt

https://github.com/launchdarkly/ldcli/assets/55991524/fe35ac14-d33e-41b8-8d03-851176469058
Adds a viewport for displaying the SDK instructions, which should be scrollable both with up/down keys as well as a mouse wheel.

feat: make sdk instructions scrollable

---

internal/quickstart/choose_sdk.go
internal/quickstart/container.go
internal/quickstart/messages.go
internal/quickstart/show_sdk_instructions.go
internal/sdks/sdk_instructions/python.md

Copies the instructions from the guided quickstart [here](https://github.com/launchdarkly/gonfalon/tree/main/static/ld/components/getStarted/sdk) as markdown files to render in the setup flow. Starting with just one SDK (python) to establish the pattern.

feat: Use new sdk instructions instead of hello READMEs

---

internal/quickstart/choose_sdk.go

I removed the extra space between the choose sdk list and the pagination dots.
bug fix: we were only showing 15 items total. This was due to setting pagination.PerPage manually to 5. We can't manually control this property without bugs due to how list.updatePagination() works. Setting the list height to 9 shows us 5 items, and displays all 24-25 items.
video: https://share.cleanshot.com/bs9YgdBF

fix: space above pagination dots and pagination bug

---

internal/quickstart/container.go
internal/quickstart/show_sdk_instructions.go

Removes mouse wheel support from the viewport, because with this enabled we're unable to highlight the text within to copy/paste (which is kinda the whole point of it).

fix: remove mouse wheel support from show sdk & show scroll options in help view

---

internal/quickstart/container.go
internal/quickstart/show_sdk_instructions.go

I noticed that when copy/pasting the sdk instructions with a border for the viewport, we end up with something like this on the clipboard: 
```
│  3. Create a file called  test.py  and add the following code:                 │
│                                                                                │
│    # Import the LaunchDarkly client.                                           │
│    import ldclient                                                             │
│    from ldclient import Context                                                │
│    from ldclient.config import Config                                          │
│                                                                                │
│    # Create a helper function for rendering messages. …
```

fix: remove side borders from show SDK viewport

---

internal/quickstart/container.go
internal/quickstart/messages.go
internal/quickstart/show_sdk_instructions.go

no need to refetch the env when re-choosing a new SDK when we already have the keys! this makes the loading of sdk steps a lot quicker if you're checking out a bunch of different sdks and going back and forth between steps

chore: don't refetch envs when going back from show sdk step

---

internal/quickstart/messages.go
internal/quickstart/toggle_flag.go

chore: show a nicer error message when toggle a flag fails

---

cmd/config/config.go

The unset flag takes a value removes it from the config file if it is relevant. It ignores arbitrary keys and for now only supports:
* access-token
* base-uri

feat: add config unset flag

---

cmd/config/config.go
internal/config/config.go

The set flag takes a key/value pair and writes them to the config file if they are relevant. It ignores arbitrary keys and for now only supports:
* access-token
* base-uri

feat: add config set flag

---

cmd/cmdtest.go
cmd/config/config.go
cmd/root.go
go.mod
go.sum
internal/config/config.go
vendor/github.com/mitchellh/go-homedir/LICENSE
vendor/github.com/mitchellh/go-homedir/README.md
vendor/github.com/mitchellh/go-homedir/homedir.go
vendor/modules.txt

Running `ldcli config --list` will read the values set in the config file. If the file doesn't exist, it's a no-op.

feat: Adds support for `ldcli config --list`

---

cmd/cmdtest.go
cmd/config/config.go
cmd/root.go
go.mod
go.sum
internal/config/config.go
vendor/github.com/mitchellh/go-homedir/LICENSE
vendor/github.com/mitchellh/go-homedir/README.md
vendor/github.com/mitchellh/go-homedir/homedir.go
vendor/modules.txt

Adds a `config` command with three flags:
* `ldcli config --list` -- shows the values in the current config file
* `ldcli config --set foo bar` -- adds the key "foo" with value "bar" to the config file if it's a relevant key
* `ldcli config --unset foo` -- removes "foo" from the config file if it exists
This PR only sets up the command with the flags and doesn't do anything yet.
Add any …

feat: Add config command

---

cmd/flags/flags.go
cmd/flags/get.go
cmd/flags/get_test.go
internal/flags/client.go
internal/flags/mock_client.go

example command on staging: `go run main.go flags get --project=very-important-project --environment=production --flag=sunny-test-flag-7`
GIF: 

feat: add get subcommand to flag

---

README.md
cmd/config/config.go
cmd/root.go
internal/config/config.go

Running `ldcli config --list`, `--set foo bar`, or `--unset foo` without a config file should not error now.
If we keep it in the home directory instead of in a nested one, we don't need to worry about creating the directory if it does not exist.

fix: Change config file location

---

cmd/config/config.go
cmd/config/config_test.go
cmd/config/testdata/help.golden

Running `ldcli config` without a flag didn't show anything. Now it shows the help text like other commands.

fix: Show help when running `ldcli config`

---

internal/analytics/client.go
internal/quickstart/messages.go

If using a structurally valid URL but semantically wrong, the analytics tracking would try to read from a nil response which would panic.

fix: Don't panic with nil tracking response body

---

cmd/projects/list.go
cmd/projects/list_test.go
internal/output/multiple_outputter.go
internal/output/multiple_outputter_test.go
internal/output/output.go
internal/output/singular_outputter_test.go

Use the output flag to show either JSON or plaintext for a command's response with multiple resources.
This only works for projects list, but another PR will add support to the rest of the commands.

feat: output flag multiple resources

---

cmd/resource_cmds.go
cmd/resource_cmds_test.go
cmd/resources/resources.go
cmd/root.go

Adds a hardcoded implementation of the `NewResourceCmd` and `NewOperationCmd` functions that we plan to generate in the future. 
Calling help:
```shell
$ go run main.go teams create --help
Create a team. To learn more, read [Creating a team](https://docs.launchdarkly.com/home/teams/creating).
LaunchDarkly supports four fields for expanding the "Create team" response. By default, these fields are **not** included in the response.
To expand the response, append the `expand` query parameter and add a comma-separated list with any of the following fields:
* `members` includes the total count of members that belong to the team.
* `roles` includes a paginated list of the custom roles that you have assigned to the team.
* `projects` includes a paginated list of the projects that the team has any …
```

feat: hardcoded resource cmds

---

cmd/cliflags/flags.go
cmd/config/config.go
cmd/config/testdata/help.golden
cmd/environments/environments.go
cmd/flags/flags.go
cmd/members/members.go
cmd/projects/projects.go
cmd/root.go
internal/analytics/client.go
internal/config/config.go

1. adds a new `analytics-opt-out` flag
a. this value can be set as an environment variable (`LD_ANALYTICS_OPT_OUT`), config value, or passed as a flag
b. this value can be set as `0` or `false` for false, `1` or `true` for true
2. will not send a tracking event if this value is set to true
Manually tested, was unsure how to update tests for this 🤔

feat: allow users to opt out of analytics tracking

---

cmd/config/config.go
cmd/validators/validators.go
internal/config/config.go
internal/config/config_test.go
internal/output/output.go

This PR has two things (please forgive me):
1. allows saving the output flag value in the config file
2. fixes a bug where the analytics-opt-out flag value in the config file would panic

feat: output in config

---

cmd/resource_cmds.go
cmd/resource_cmds_test.go
cmd/resources/resources.go
cmd/root.go

admittedly this probably didn't need to be its own PR, but we've added logging!
adds `teams get --teamKey {team key}`
note that the flag is camelcase, but that's how it comes from the openapi spec. we'll update this once we do the generation of OperationDate from the OpenAPI spec (comment left)

feat: add hardcoded operation command with no body

---

cmd/flags/create.go
cmd/flags/update.go
internal/output/output.go
internal/output/output_test.go

Show a success message after creating or updating a resource with a plaintext output.

feat: plaintext success response

---

cmd/environments/get.go
cmd/flags/create.go
cmd/flags/get.go
cmd/flags/update.go
cmd/members/create.go
cmd/members/invite.go
cmd/projects/create.go
cmd/projects/list.go
internal/errors/errors_test.go
internal/output/resource_output.go
internal/output/resource_output_test.go

Running the `members create` command with invalid JSON would show a bad error:
```
json: cannot unmarshal object into Go value of type []members.MemberInput
```
Now it shows a nicer one:
```
$ ldcli members create --data '{"email": "friend+11@launchdarkly.com", "role": "writer"}'
invalid JSON
$ ldcli members create --data '{"email": "friend+11@launchdarkly.com", "role": "writer"}' --output json
{"message":"invalid JSON"}
```
Provide a clear and concise description of any alternative solutions or features you've …

fix: Fix data flag JSON error handling

---

README.md
cmd/cliflags/flags.go
cmd/config/config.go
cmd/config/config_test.go
cmd/config/testdata/help.golden
cmd/root.go

Running `ldcli config --help` shows
```
View and modify specific configuration values
Current settings:
- `access-token`: LaunchDarkly access token with write-level access
- `analytics-opt-out`: Opt out of analytics tracking
- `base-uri`: LaunchDarkly base URI
- `output`: Command response output format in either JSON or plain text
Usage:
ldcli config [flags]
Flags:
-h, --help           help for config
--list           List configs
--set            Set a config field to a value
--unset string   Unset a config field
Global Flags:
--access-token string   LaunchDarkly access token with write-level access
--analytics-opt-out     Opt out of analytics tracking
--base-uri string       LaunchDarkly base URI (default "https://app.launchdarkly.com")
-o, --output string         Command response …
```

feat: Add valid config fields to its help

---

cmd/quickstart.go
cmd/root.go
internal/analytics/client.go
internal/quickstart/container.go
internal/quickstart/messages.go

Added the `cli setup started` event specifically.
- Created a eventTrackedMsg and trackSetupStartedEvent function to send cmd. 
- All trackSetupStartedEvent function calls happen within container
gif:

feat: track cli setup started event

---

internal/analytics/client.go
internal/quickstart/container.go
internal/quickstart/messages.go

- **added client methods**
- **track sdk selected in container**

feat: track sdk selected on setup

---

cmd/cmdtest.go
cmd/environments/get_test.go
cmd/flags/create_test.go
cmd/flags/get_test.go
cmd/flags/update_test.go
cmd/members/create_test.go
cmd/members/invite_test.go
cmd/projects/create_test.go
cmd/projects/list_test.go
cmd/validators/validators.go
cmd/validators/validators_test.go

When a flag that can be set in the config file is missing, show additional text to guide the user to add that flag to the config.
Without `access-token` set:
```
$ ldcli flags get
required flag(s) "access-token", "environment", "flag", "project" not set.
Use `ldcli config --set access-token <value>` to configure the value to persist across CLI commands.
See `ldcli flags get --help` for supported flags and usage.
```
With `access-token` set:
```
$ ldcli flags get --access-token foo
required flag(s) "environment", "flag", "project" not set. See `ldcli flags get --help` for supported flags and usage.
```
Provide a clear and …

feat: Add additional help text with missing access-token

---

cmd/config/config.go

Show an error message for `ldcli config --unset {key}` and `ldcli config --set {key} {val}` when key is invalid.
```
$ ldcli config --set analytics-opt-out true foo bar
foo is not a valid configuration option
$ ldcli config --unset foo
foo is not a valid configuration option
```

fix: config action output

---

cmd/root.go

The values in viper haven't been set at the time we read them for this call, so we need to check the root command's flags for the current values.

fix: Pass in values to analytics tracker for command completed event

---

internal/sdks/sdk_instructions/android.md
internal/sdks/sdk_instructions/dotnet-server.md
internal/sdks/sdk_instructions/go.md
internal/sdks/sdk_instructions/haskell-server.md
internal/sdks/sdk_instructions/ios-swift.md
internal/sdks/sdk_instructions/java.md
internal/sdks/sdk_instructions/js.md
internal/sdks/sdk_instructions/node-server.md
internal/sdks/sdk_instructions/php.md
internal/sdks/sdk_instructions/python.md
internal/sdks/sdk_instructions/roku.md
internal/sdks/sdk_instructions/ruby.md
internal/sdks/sdk_instructions/rust.md

Updated SDK instructions based on recent updates.

feat: update sdk instructions

---

internal/resources/client.go

The generated resources use an HTTP client instead of the LD go client, so an error response will be a regular JSON string and not have all the methods for an `APIError`.

fix: Return regular error for generated resource error response

---

internal/output/plaintext_fns.go
internal/output/resource_output_test.go

A delete response won't have a body, so we'll only have the resource's key to show in a success response.

fix: Fix delete message output with only a key

---

README.md

[SC-243155](https://app.shortcut.com/launchdarkly/story/243155/ldcli-readme-add-link-back-to-product-docs)
Ben [suggested](https://launchdarkly.slack.com/archives/C06KW03D8F7/p1715027472514309?thread_ts=1715026459.004739&cid=C06KW03D8F7) that we link to the product docs from here. Those docs don't currently have additional info, but eventually they will, and they help you discover more info about LaunchDarkly generally.

docs: add link to docs.launchdarkly

---

internal/output/plaintext_fns.go
internal/output/resource_output.go
internal/output/resource_output_test.go

When a response looks like this:
```
{
"items": [
{
"_id": "test-id",
"name": "test-name"
}
]
}
```
Plain text output should look like
```
* test-name (test-id)
```
instead of
```
* test-name (%!!(MISSING)s(<nil>))
```

fix: Handle output for multiple resources with _id and name

---

internal/quickstart/show_sdk_instructions.go

Fixes spelling of 'environment' in SDK setup steps.

fix: typo in SDK setup steps

---

internal/resources/client.go

our 3 second timeout was resulting in some errors - instead we'll rely on gonfalon's timeout. 
```
Get "https://app.launchdarkly.com/api/v2/approval-requests": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

fix: remove http client timeout for resources

---

cmd/resources/resources.go

somehow the help/usage on the root command seems to have taken precedence over the subcommands help templates. setting it manually seems to fix this (which we do already for operation commands). 
ideally we'd have some kind of shared template between the resource and operation cmds since they are very similar, but I couldn't quite figure out how to hide the required/optional flags because technically the resource commands all do have a flag (`help`) so that section isn't properly hiding. i'm trying to play with more template functions but couldn't quite get them to work, and I really want to fix this for people to test. 
before:
after:

fix: set resource cmd usage template

---

cmd/flags/toggle.go
cmd/resources/resources.go
cmd/root.go
cmd/templates.go

updates the operation usage template to only show a header for required/optional flags if they're actually there. also removes the template for resources in favor of this singular template now. 
truly don't know if this is the Best Way to handle this as I'm not familiar with templates, but it works!
before:
after:
and also resources work now too, though to be honest I don't know how `Flags:` is showing up there 🤔

fix: update usage template to only show flags when present

---

internal/output/output.go
internal/output/resource_output.go
internal/output/resource_output_test.go

The tags endpoint returns data like this:
```
{
"items": [
"tag1"
],
"_links": {
"self": {
"href": "/api/v2/tags",
"type": "application/json"
}
},
"totalCount": 1
}
```
so we need to handle a response that has a list of scalar values for items instead of JSON objects.

fix: Show plaintext list of tags

---

cmd/members/invite.go
cmd/members/invite_test.go
cmd/members/members.go
cmd/root.go

This was accidentally removed when we generated the remaining resources from the openapi spec
Running `ldcli members --help` shows the new command:
```
Usage:
ldcli members [command]
Available Commands:
create       Invite new members
create-teams Add a member to teams
delete       Delete account member
get          Get account member
invite       Invite new members
list         List account members
update       Modify an account member
Global flags:
-h, --help                  Get help about any command
--access-token string   LaunchDarkly access token with write-level access
--analytics-opt-out     Opt out of analytics tracking
--base-uri string       LaunchDarkly base URI (default "https://app.launchdarkly.com")
-o, --output string         Command response output format in either JSON …
```

fix: add back member invite alias

---

cmd/members/invite.go

```Create new members and send them an invitation email
Usage:
ldcli members invite [flags]
Required flags:
-e, --emails strings   A comma separated list of emails
Optional flags:
-r, --role string   Built-in role for the member - one of reader, writer, or admin (default "reader")
Global flags:
-h, --help                  Get help about any command
--access-token string   LaunchDarkly access token with write-level access
--analytics-opt-out     Opt out of analytics tracking
--base-uri string       LaunchDarkly base URI (default "https://app.launchdarkly.com")
-o, --output string         Command response output format in either JSON or plain text (default "plaintext")```

fix: add required flags for member invite cmd

---

internal/config/config_test.go
internal/output/output.go

PR feedback in https://github.com/launchdarkly/ld-docs-private/pull/4370 recommended we tell folks how to set their `output` preference using the `config` command. In testing that out, I wanted `ldcli` to tell me what the available options were. Instead, I had to search this repo to figure it out. 
This PR adds the available options to the error msg.
Definitely open to other ideas on where to surface this.

docs: update output error msg

---

cmd/root.go
cmd/templates.go

running `ldcli completion`
```
Generate the autocompletion script for ldcli for the specified shell.
See each command's help for details on how to use the generated script.
Usage:
ldcli completion [command]
Available Commands:
bash        Generate the autocompletion script for bash
fish        Generate the autocompletion script for fish
powershell  Generate the autocompletion script for powershell
zsh         Generate the autocompletion script for zsh
Global flags:
-h, --help                  Get help about any command
--access-token string   LaunchDarkly access token with write-level access
--analytics-opt-out     Opt out of analytics tracking
--base-uri string       LaunchDarkly base URI (default "https://app.launchdarkly.com")
-o, --output string         Command response output format …
```

fix: completion cmd usage & short description

---

cmd/flags/archive.go
cmd/flags/archive_test.go
cmd/root.go

`ldcli flags --help`
```
Usage:
ldcli flags [command]
Available Commands:
archive                        Archive a feature flag
copy                           Copy feature flag
create                         Create a feature flag
create-migration-safety-issues Get migration safety issues
delete                         Delete feature flag
get                            Get feature flag
get-status                     Get feature flag status
get-status-across-environments Get flag status across environments
list                           List feature flags
list-expiring-context-targets  Get expiring context targets for feature flag
list-expiring-user-targets     Get expiring user targets for feature flag
list-statuses                  List feature flag statuses
toggle-off …
```

feat: add archive flag cmd

---

cmd/cliflags/flags.go
cmd/config/config.go
cmd/config/testdata/help.golden
internal/config/config.go
internal/config/config_test.go

Config file supports new keys.
```
ldcli config --set environment production
ldcli config --set flag my-flag
ldcli config --set project default
```
Running `ldcli config --list` returns
```
environment: production
flag: my-new-flag
project: default
```
Now commands that require these flags can use the values in the config file:
```
ldcli flags get # uses --project and --flag
ldcli environments get # uses --environment
```
Provide a clear and concise description of any alternative solutions or features you've …

feat: support default resources in config

---

cmd/config/config.go

Show success/error message after setting/unsetting a config value.
```
$ ldcli config --set environment production --set project default
Successfully updated
* environment
* project
$ ldcli config --set environment production --set project default --output json
{"items":["environment","project"]}
$ ldcli config --set invalid production
invalid is not a valid configuration option
$ ldcli config --set invalid production --output json
{"message":"invalid is not a valid configuration option"}
$ ldcli config --unset project
Successfully deleted project
$ ldcli config --unset project --output json
{"key":"project"}
$ ldcli config --unset invalid
invalid is not a valid configuration option
$ ldcli config --unset invalid --output json
{"message":"invalid is not a valid configuration option"}
``` …

feat: config feedback

---

README.md

Remove the "Caution" section of the README just before we release v1.0. Please advise on when this should be merged.

chore: remove "prerelease" from readme

---

cmd/resources/resources.go

While the data flags *were* required when actually running the commands, they weren't showing up as a required flag in the help template because we hadn't added the proper annotations. Fixed now!

fix: add required annotation to data flags

---

internal/quickstart/choose_sdk.go
internal/quickstart/container.go
internal/quickstart/help.go

Can filter the SDK names.
* When viewing the list of SDKs, press "/" to open the filter prompt
* To close the filter prompt, press "/" again

feat: Filter SDKs with /

---

.github/workflows/go.yml
CONTRIBUTING.md
Makefile
git/hooks/pre-commit
go.mod

Adds CI checks for:
- `gofmt`: important to ensure code is always formatted in the repo
- `go mod tidy`: important to ensure deterministic dependencies
It does this via `git/hooks/pre-commit`, which can also be installed via `make install-hooks`.

ci: enforce formatting, go mod tidy

---

cmd/resources/resource_cmds.go
cmd/resources/resource_cmds.tmpl
cmd/resources/resources.go

Creating a new renderer for each generated resource action is slow, so we can create a single one and pass it into each function that needs it. This reduces the call to `AddAllResourceCmds` from over five seconds to a few hundred ms.

fix: Pass in markdown renderer to speed up command

---

.goreleaser.yaml

Realized too late that we need to specify building a windows binary in the goreleaser config. The [latest release](https://github.com/launchdarkly/ldcli/releases/tag/v1.1.0) doesn't have a windows binary.

fix: Build windows binary

---

.github/workflows/check-openapi-updates.yml

chore: Send slack notification on failure

---

cmd/config/config.go
cmd/login/login.go
internal/config/config.go
internal/config/config_test.go

If the user already has an access token, don't let them log in again.
Since access tokens count against an account's limit, we don't want to let the user create endless access tokens by running the login command over and over. This prevents them from creating a new one but gives them a way to do it if they really want to.

feat: sc-240965/check current access token

---

internal/login/login.go
internal/login/login_test.go

During login, after receiving a verification URL, we can make a request to it and, after the user has allowed access, it returns an access token.
Additional PRs will poll the endpoint and handle the various errors it can return.

feat: Can fetch a token based on the device code

---

cmd/login/login.go
internal/login/login.go
internal/login/login_test.go

Attempt to fetch an access token from the `POST /tokens` endpoint. It retries every second if the request is pending up to two minutes while the user logs in to LD to approve their request. Other errors show a specific error message so the user knows what to do.

feat: sc-240964/fetch token

---

internal/dev_server/adapters/api.go
internal/dev_server/adapters/middleware.go
internal/dev_server/adapters/sdk.go
internal/dev_server/dev_server.go

can create project

---

internal/dev_server/api/api.yaml
internal/dev_server/api/server.gen.go
internal/dev_server/api/server.go
internal/dev_server/db/sqlite.go
internal/dev_server/dev_server.go
internal/dev_server/model/store.go

I'm unclear why there were so many formatting changes in the api.yaml file.

Adding get project by project key

---

internal/dev_server/api/api.yaml
internal/dev_server/api/server.gen.go
internal/dev_server/api/server.go
internal/dev_server/db/sqlite.go
internal/dev_server/model/store.go

I hid the overrides behind an expand flag so that we wouldn't return this by default in the cli.  The project response is already very long since I'm now returning the flag state so I preemptively put the overrides behind the expand flag.  
To test:
`GET localhost:8765/dev/projects/default?expand=overrides`
will add something like this to the response
```
"overrides": {
"enable-flag-code-references": {
"value": false,
"version": 1
}
},
```

Add overrides to projects

---

internal/dev_server/api/server.go
internal/dev_server/db/sqlite.go
internal/dev_server/model/project.go
internal/dev_server/model/store.go
internal/dev_server/sdk/get_client_flags.go
internal/dev_server/sdk/stream_client_flags.go
internal/dev_server/sdk/stream_server_flags.go

Load overrides when the SDKs load. Made the store less efficient but easier to reuse in the two scenarios we have.

fix: Overrides weren't being loaded when SDKs were initialized

---

internal/dev_server/api/Makefile
internal/dev_server/api/server.go
internal/dev_server/dev_server.go
internal/dev_server/ui/asset_handler.go

Adds UI routes & uses go generate instead of make for regenerating the server code.

feat: add ui routes

---

cmd/dev_server/projects.go
internal/dev_server/api/api.yaml
internal/dev_server/api/server.gen.go
internal/dev_server/api/server.go
internal/dev_server/db/sqlite.go
internal/dev_server/model/project.go
internal/dev_server/model/store.go

I've added a sync api for the project that refetches the flag state.
The api looks like this 
`PATCH localhost:8765/dev/projects/default/sync?expand=overrides`
I've updated it so that the expand param is in both the patch and post apis since we'll want that data for the ui.  
In the next pr, I'll add another endpoint to patch the context and source environment for the project.  I should also do a bit of refactoring.  😬

Adds a sync api

---

cmd/cliflags/flags.go
cmd/config/testdata/help.golden
cmd/dev_server/dev_server.go
cmd/dev_server/start_server.go
internal/config/config.go
internal/config/config_test.go
internal/dev_server/dev_server.go

To set the value in the config file:
`go run . config --set dev-stream-uri https://relay-stg.ld.catamorphic.com`
This can also be set as an environment variable:
`export LD_DEV_STREAM_URI=https://relay-stg.ld.catamorphic.com`
Value defaults to prod: `https://stream.launchdarkly.com`
```
$ go run . config help
View and modify specific configuration values
Supported settings:
- `access-token`: LaunchDarkly access token with write-level access
- `analytics-opt-out`: Opt out of analytics tracking
- `base-uri`: LaunchDarkly base URI
- `dev-stream-uri`: URI from which the dev server will stream flag configurations
- `environment`: Default environment key
- `flag`: Default feature flag key
- `output`: Command response output format in either JSON or plain text
- `project`: Default project key …
```

add dev stream uri to config file

---

README.md

Updates the location of where the config file is stored.

fix: Update readme about where config file is stored

---

cmd/dev_server/dev_server.go
cmd/dev_server/start_server.go
internal/dev_server/dev_server.go

`go run . dev-server ui` should pop open a new browser window for the UI
also adds a log line when the server starts to include those instructions as well ✨

add UI cmd

---

internal/dev_server/api/api.yaml
internal/dev_server/api/server.gen.go
internal/dev_server/api/server.go

the ldcli handles errors more nicely when they include an expected rep - added that to our server so that they display more nicely:
```
$ go run . dev-server remove-project --project does-not-exist
project not found (code: not_found)
```

fix error response expected by ldcli cmds

---

internal/dev_server/adapters/sdk.go
internal/dev_server/api/server.go
internal/dev_server/db/sqlite.go
internal/dev_server/model/store.go
internal/dev_server/sdk/get_client_flags.go
internal/dev_server/sdk/get_server_flags.go
internal/dev_server/sdk/store_facade.go
internal/dev_server/sdk/stream_client_flags.go
internal/dev_server/sdk/stream_server_flags.go

Improves error handling when an sdk connects and a project is missing.
Previous behavior was a scary panic log. Now there's a more helpful
```
2024/06/28 16:26:02 project, default2, not found
2024/06/28 16:26:02 You may need to call ldcli dev-server add-project
```

fix: error handling when project is missing

---

cmd/config/config.go
internal/config/config.go
internal/config/config_test.go
internal/output/output.go

Consolidate config actions to use the same underlying struct type and methods. This should simplify how values are set and unset by removing a layer of unmarshaling.

chore: Simplify config

---

internal/dev_server/api/api.yaml
internal/dev_server/model/observer.go
internal/dev_server/model/observer_test.go

- [?] I have validated my changes against all supported platform versions
N/A
Used a sync map because there's a data race using a non-synchronized one.

fix: use sync map for observers

---

cmd/login/login.go
cmd/root.go
internal/analytics/client.go

The login command doesn't have an existing access token, so the normal path for tracking analytics doesn't work. We would have to add an unauthorized endpoint to track analytics or do some manual work to allow both unauthed and authed requests in the same endpoint.

chore: Remove analytics for login

---

cmd/cliflags/flags.go
cmd/dev_server/dev_server.go
cmd/dev_server/start_server.go
internal/dev_server/dev_server.go

When you run the command you can add a `port` flag to specify something other than `8675` for it to run on. If none is provided, it will use the default we had hardcoded before.

feat: Allow for the customization of the port when starting dev server

---

.github/variables/go-versions.env
.github/workflows/go-versions.yml
.github/workflows/go.yml
.github/workflows/manual-publish.yml
.github/workflows/release-please.yml
go.mod
go.sum

Currently we are building with whatever Go version is installed on the runner at the time of the build. At the same time, we're testing with a particular Go version in CI.
This PR unifies the versions used in test and build. That way we know we've tested what we're shipping.

fix(deps): use consistent Go version in builds and CI

---

internal/dev_server/api/api.yaml
internal/dev_server/api/server.gen.go
internal/dev_server/api/server.go

Add validation to the POST endpoint to verify they have a sourceEnvironmentKey, and throw a 400 if they don't.

fix: Return 400 if sourceEnvironmentKey is not present in Post endpoint

---

cmd/root.go
internal/config/config.go

When running a command, if there isn't a config file then create one. Since most users will not want to specify their access token, etc. for each command, we can assume they will want a config file.
If we can't write the config file, fail silently. Then when running any `config` commands, the error will give more details.
You can test this by deleting or moving the `~/.config/ldcli/config.yml` file and running `ldcli config --list`.
Provide a clear and concise description of any alternative solutions or …

fix: Create config file if it does not exist

---

internal/dev_server/api/api.yaml
internal/dev_server/api/server.gen.go
internal/dev_server/api/server.go
internal/dev_server/db/sqlite.go
internal/dev_server/db/sqlite_test.go
internal/dev_server/model/error.go
internal/dev_server/model/store.go

Return a 409 when a project already exists in the dev server (vs. 500).

fix: Don't 500 when there's a preexisting project

---

internal/quickstart/show_sdk_instructions.go

Since switching to using the sdkmeta library, each SDK name has "SDK" in it. The placeholder for fetching the SDK instructions doesn't need "SDK" in it now.
This is what it looks like after the change:

fix: Remove stutter from "fetching {sdk name} SDK SDK"

---

Dockerfile.goreleaser

Use ubuntu as the base image. With alpine, because it has none of the standard shared libraries installed, we were running into the following issue.
```
ldd ldcli
/lib/ld-linux-aarch64.so.1 (0xffffb7229000)
Error loading shared library libresolv.so.2: No such file or directory (needed by ldcli)
libpthread.so.0 => /lib/ld-linux-aarch64.so.1 (0xffffb7229000)
libdl.so.2 => /lib/ld-linux-aarch64.so.1 (0xffffb7229000)
libc.so.6 => /lib/ld-linux-aarch64.so.1 (0xffffb7229000)
Error relocating ldcli: fcntl64: symbol not found
Error relocating ldcli: __res_search: symbol not found
```
This in turn, caused `ldcli` to not be executable from the image.
By using ubuntu, standard c libraries are pre-installed, so we won't have this issue. 
We probably do want to investigate the build process to see if …

fix: Use ubuntu for the base image

---

cmd/templates.go

This adds a note in the usage text about the dev-server command.
example
```
❯ go run . --help
LaunchDarkly CLI to control your feature flags
Usage:
ldcli [command]
Commands:
setup                         Create your first feature flag using a step-by-step guide
config                        View and modify specific configuration values
completion                    Enable command autocompletion within supported shells
login                         Log in to your LaunchDarkly account
dev-server                    Run a development server to serve flags locally
Common resource commands:
flags                         List, create, and modify feature flags and their targeting
environments                  List, create, and manage environments
projects                      List, create, and …
```

fix: Add dev server to usage template

---

internal/dev_server/api/error_handlers.go
internal/dev_server/dev_server.go

This makes it so that errors from the dev server are propagated back to the CLI in a way that the CLI can reasonably render. This way, we can return something that gives the user an idea of what went wrong vs. a generic "unexpected error" message.
example
```
❯ ldcli dev-server add-project --project jimbo-jones --source staging
unable to get SDK key from LD API: 404 Not Found (code: internal_server_error)
```

fix: Propagate dev server errors in CLI compatible format

---

internal/dev_server/ui/package-lock.json
internal/dev_server/ui/package.json
internal/dev_server/ui/src/App.css
internal/dev_server/ui/src/App.tsx
internal/dev_server/ui/src/Flags.tsx

feat: Display source environment in LaunchDevly UI

---

internal/dev_server/adapters/api.go
internal/dev_server/adapters/api_test.go
internal/dev_server/adapters/mocks/api.go
internal/dev_server/api/api.yaml
internal/dev_server/api/server.gen.go
internal/dev_server/api/server.go
internal/dev_server/db/sqlite.go
internal/dev_server/db/sqlite_test.go
internal/dev_server/dev_server.go
internal/dev_server/model/environments.go
internal/dev_server/model/project.go
internal/dev_server/model/variations.go
internal/dev_server/ui/src/App.tsx
internal/dev_server/ui/src/ContextEditor.tsx
internal/dev_server/ui/src/EnvironmentSelector.tsx
internal/dev_server/ui/src/Flags.tsx
internal/dev_server/ui/src/ProjectEditor.tsx
internal/dev_server/ui/src/SubmitButton.tsx
internal/dev_server/ui/src/api.ts
internal/dev_server/ui/src/types.ts

https://www.loom.com/share/547246f3f0384ff69260bd744e9dd392

feat: Implement environment update functionality in launchdevly ui

---

internal/dev_server/ui/src/EnvironmentSelector.tsx
internal/dev_server/ui/src/Flags.tsx

Previously, the search bar didn't clear when the clear button was clicked.

fix: LaunchDevly: Search clear not clearing filter

---

internal/dev_server/ui/src/Flags.tsx

Fixes the interaction with pagination when toggling the "only" toggle.  Puts the filter ahead of the display logic so that our pagination doesn't get confused why the render is leaving flags out.  
This works as expected now.

fix: LaunchDevly: Pagination for 'Only show flags with overrides'

---

internal/dev_server/adapters/api.go

Previously we were doing `numFlags / 20` requests  to fetch all flags.  This was pretty slow.  A page size of 100 is much more performant.  (For our env, query time went from roughly 12 seconds to like 4, meaning a lot of the overhead was network related, which we just cut by a factor of 5.)

chore: Set default flag pagination size to 100

---

internal/dev_server/ui/src/Flags.tsx

Previously you could get stuck in an error state where the "only show overrides" checkbox would get locked to on, and then disabled so that you couldn't edit it again due to having no overrides.  
I solved this by adding a cheap useEffect hook that checks for this condition and directs us into a valid state. 
I thought about hooking this in in various places to avoid the useEffect usage, but a global watcher for this component made the most sense to me.

fix: LaunchDevly: Cleanup code and remove only show overrides when there are no overrides

---

cmd/dev_server/dev_server.go
cmd/dev_server/flags.go
cmd/dev_server/projects.go

```
update the specified project and its flag configuration with the LaunchDarkly Service
Usage:
ldcli dev-server update-project [flags]
Required flags:
--project string   The project key
Optional flags:
--context string   Stringified JSON representation of your context object ex. {"user": { "email": "test@gmail.com", "username": "foo", "key": "bar"}}
--source string    environment to copy flag values from
Global flags:
-h, --help                  Get help about any command
--access-token string     LaunchDarkly access token with write-level access
--analytics-opt-out       Opt out of analytics tracking
--base-uri string         LaunchDarkly base URI (default "https://app.launchdarkly.com")
--dev-stream-uri string   Streaming service endpoint that the dev server uses to obtain …
```

feat: Add command to launchDevly to update the project environment and context

---

cmd/dev_server/dev_server.go
internal/dev_server/adapters/api.go
internal/dev_server/adapters/mocks/api.go
internal/dev_server/api/api.yaml
internal/dev_server/api/get_environments.go
internal/dev_server/api/server.gen.go
internal/dev_server/model/environments.go
internal/dev_server/model/project_test.go
internal/dev_server/sdk/go_sdk_test.go
internal/dev_server/ui/src/EnvironmentSelector.tsx
internal/dev_server/ui/src/Flag.tsx
internal/dev_server/ui/src/ProjectEditor.tsx
internal/dev_server/ui/src/SubmitButton.tsx
internal/dev_server/ui/src/Switch.css
internal/dev_server/ui/src/api.ts

We now query environments by name, instead of all X at once up front.

fix: Context updating, environment rate limiting, toggle styling

---

cmd/resources/resource_cmds.go
ld-openapi.json

Adds the following resources:
```
ai-configs-beta
approvals-beta
experiments*
flag-import-configurations-beta
holdouts-beta
insights-charts-beta
insights-deployments-beta
insights-flag-events-beta
insights-pull-requests-beta
insights-repositories-beta
insights-scores-beta
layers
persistent-store-integrations-beta
*taken out of beta
```
AI Configs:
test a command:
```
$  go run main.go ai-configs-beta list-ai-configs
* AI Configs dogfood (For Testing) (ai-configs-dogfood)
Showing results 1 - 1 of 1.
```
Provide …

feat: add new resources & commands from updated openapi spec

---

.github/workflows/check-openapi-updates.yml

The Slack hook isn't working yet, but it's still worth having it run daily (not every 5 min!)

ci: Change github action cron

---

cmd/cliflags/flags.go
cmd/config/testdata/help.golden
cmd/dev_server/start_server.go
internal/dev_server/model/sync.go
internal/dev_server/model/sync_test.go

https://launchdarkly.atlassian.net/browse/FUN-447
Added a `should-sync` flag to the server startup command that sets `model.InitialProjectSettings.Enable` which controls whether [this function ](https://github.com/launchdarkly/ldcli/blob/FUN-447-start-n-sync-dont-blow-away-existing-db/internal/dev_server/model/sync.go#L24) no-ops or not.
Using the no-op made sense for the persistent volumes use case, since all the project and env data will already exist locally, but open to being more surgical if so desired.
We could skip the `UpdateProject` call specifically in the `CreateOrSyncProject` function, which does the sync bit. Then we'd have to decide if we still want to do …

feat: Skip syncing on start if flag set

---

cmd/cliflags/flags.go
cmd/config/testdata/help.golden

fix: Correct sync once description

---

internal/dev_server/db/backup/sqllite_backup.go
internal/dev_server/db/sqlite.go
internal/dev_server/sdk/http_test.go
internal/dev_server/sdk/project_key_middleware.go

Closes https://github.com/launchdarkly/ldcli/issues/490
Supports the `api_key ` prefix on keys used for authentication.

fix: Handle api_key prefix in auth header

---

.github/workflows/go.yml
.github/workflows/manual-publish.yml
.github/workflows/release-please.yml

Most builds are failing right now. This is due to a pre-commit timeout when the go module cache is refreshed. This moves the go build to the first step. That makes go build refresh the module cache and makes it so that pre-commit won't need to, avoiding the timeout.

chore: Go Build first

---

.github/dependabot.yml

Turns out that dependabot change was invalid and auto-merge isn't a concept.

chore: Revert "chore: Update dependabot configuration for auto-merge"

---

.github/actions/publish/action.yml

This corrects the docker login command to not accept the password via stdin. The command needs to be done on the container, not on the host.
---
Related Jira issue: [FUN-804: Release new ldcli](https://launchdarkly.atlassian.net/browse/FUN-804)

fix(ci): [FUN-804] docker login command

---

cmd/root.go
cmd/sourcemaps/sourcemaps.go
cmd/sourcemaps/upload.go
cmd/sourcemaps/upload_test.go

* Add analytics tracking to sourcemaps command
* Improve help text of `ldcli sourcemaps`
Local Testing:

fix: improve help text and add analytics

---

README.md
internal/output/plaintext_fns.go
internal/output/resource_output.go

It seems that the flags `get-status` command was consistently returning `"cannot read resource"` when it should, of course, be returning the flag status. This turned out to be because we were not handling the parsing of the body correctly:
```
{
"name":"inactive",
"lastRequested":null,
"_links":{
"parent":{
"href":"/api/v2/flags/default/sample-flag",
"type":"application/json"
},
"self":{
"href":"/api/v2/flag-statuses/default/sample-environment/sample-flag",
"type":"application/json"
}
}
}
```
We were failing to parse out the `"name"` field where neither `"key"`, `"id"`, or `"email"` was specified.
Also stripped some whitespace off the output for cleanliness' sake and added instructions to the README on running locally.
---
Related Jira issue: [REL-8702: ldcli flags …

fix: [REL-8702] fix flags get-status command

---

README.md
cmd/root.go
internal/output/plaintext_fns.go
internal/output/resource_output.go

We were returning a 0 exit status when the API was erroring out (reported [here](https://github.com/launchdarkly/ldcli/issues/554)). This just sets the exit code
---
Related Jira issue: [REL-8111: Investigate and fix ldcli not returning non-zero error code on failure](https://launchdarkly.atlassian.net/browse/REL-8111)

fix: [REL-8111] [rel-8111] investigate and fix ldcli returning zero error code on failure
